# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
          name: Build Docker image
          command: docker build -t reload/lumturio-jira:test .

      - run:
          name: Test Docker image
          command: docker run --rm reload/lumturio-jira:test php /opt/lumturio-jira/lumturio-jira.phar --no-interaction --version
